### ISSUE TITLE
Doc issue with foundation/lazycolumn/ page

### ISSUE THREAD

**Issue by ladylazy9x** [Foso/Jetpack-Compose-Playground#67]
Plz explain this part
` { item ->
            Log.d("COMPOSE", "This get rendered $item")
            when (item) { `

And it seem missing some thing before when?

**Comment by Foso** [comment]
When LazyColumn gets displayed on the screen. item will be "A", because its the first entry in the list you set to items. Then you create a Composable for that. If that Composable doesnt fill the whole LazyColumn, the function will be triggered  with the next value ("B"). Then you create a Composable for that. When the two Composables fill the whole LazyColumn, nothing else will be happen. When you start scrolling down, the function will be triggered again, now with the value "C" . 

You can find the whole code here:
https://github.com/Foso/Jetpack-Compose-Playground/blob/master/mysamples/src/main/java/de/jensklingenberg/jetpackcomposeplayground/mysamples/github/foundation/LazyColumnDemo.kt
